### ISSUE TITLE
Create a generic `ChipGroup` component

### ISSUE THREAD

**Issue by damonbauer** [illright/attractions#248]
I'd like to render a group of `<Chip>` instances.

My current options:

* resort to using a `<CheckboxChip>` or a `<RadioChip>`
* wrap my group of `<Chip>` instances in a container, and I have handle the group styles & chip spacing.

I'd love have a `<ChipGroup {items} name="group1" />`m just like there's a `<RadioChipGroup {items} name="group1" />`.

**Comment by illright** [comment]
Yeah, maybe this could be useful after all. What styles would you like to see in this component? And what Sass variables maybe?

I'm seeing something like:
```scss
display: flex;
flex-wrap: wrap;

:global .chip:not(:first-child) {
  margin-left: .3em;  // or maybe have that be a variable
}
```
